
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monkey?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123321
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 3
        max-active: 10
        max-wait: 5000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml                      # mapper 所在包
  configuration:
    map-underscore-to-camel-case: true                          # 下划线自动映射为驼峰式

logging:
  level:
    com.jiea.bull.dao : debug                                  # 输出 mybatis 日志
